<?php

/**
 * @file
 * Contains remember_files.module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implement hook_theme().
 */
function file_history_theme($existing, $type, $theme, $path) {

  $variables = array(
    'file_history' => [
      'render element' => 'element',
    ],
  );

  return $variables;
}

/**
 * Form submission handler for upload action on file_history elements.
 */
function file_history_file_submit($form, FormStateInterface $form_state) {
  // No action is needed here for the upload button, because all file uploads on
  // the form are processed by \Drupal\file_history\Element\FileHistory::valueCallback()
  // regardless of which button was clicked.
  $form_state->setRebuild();
}
